version: '3'
services:
      web_app:
            image: tunghn1/firstwindowreact3
            build: 
                  context: .
                  dockerfile: Dockerfile.dev
            ports:
                  - "3000:3000"
            volumes:
                  - /home/node/app1/node_modules
                  - .:/home/node/app1
            environment:
                  - CHOKIDAR_USEPOLLING=true